version: '3.8'

volumes:
  pg_data:
  static:

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_HOST}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    build: ./backend/
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
  redis:
    image: redis:latest
    restart: unless-stopped
  celery:
    build: ./backend/
    restart: unless-stopped
    command: celery --app=currency_rate worker --loglevel=info
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - postgres
      - backend
      - redis
  nginx:
    build: ./nginx/
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static